apiVersion: agenova.io/v1alpha1
kind: Platform
metadata:
  name: demo-eks-bedrock
spec:
  adapters:
    - name: kubernetes-deployment
      id: agenova.io/deployment/kubernetes
      version: 0.1.0
    - name: agent-sandbox-runtime
      id: agenova.io/runtime/agent-sandbox
      version: 0.1.0
    - name: bedrock-backend
      id: agenova.io/model/bedrock
      version: 0.1.0
  infrastructure:
    deployment:
      name: control-plane
      adapterRef: kubernetes-deployment
      config:
        context: agenova-demo
        control-plane-image: 931228356546.dkr.ecr.ap-southeast-2.amazonaws.com/agenova-demo/control-plane@sha256:5e3e2ce88e010bb1b2e603f33e0397970dff81e179300c6f4b2e993dbdeba5a5
        image-pull-policy: Always
        namespace: agenova-system
    runtimeBackends:
      - name: primary-runtime
        adapterRef: agent-sandbox-runtime
        config:
          connection:
            mode: in-cluster
            namespace: agenova-system
          compatible-worker-image: 931228356546.dkr.ecr.ap-southeast-2.amazonaws.com/agenova-demo/worker@sha256:ec74e41c6348b4e4d10d4da3ab1ee0561d44c1e05964487adb2cc4a9c7b4ca9e
          compatible-worker-protocol: controlled-v1
    runtimeProfiles:
      - name: standard-isolated
        backendRef: primary-runtime
        config:
          isolation: dedicated
  services:
    modelBackends:
      - name: sydney-bedrock
        adapterRef: bedrock-backend
        config:
          region: ap-southeast-2
    modelProfiles:
      - name: coding-standard
        backendRef: sydney-bedrock
        config:
          model: amazon.nova-micro-v1:0
  initialPolicyRef:
    id: reference-default-deny
    version: "1"
